spring.application.name=discografia

spring.data.mongodb.uri=mongodb+srv://adminDiscografia:Admin12345@eva-u2-spring.zfbri0w.mongodb.net/discografica-db?retryWrites=true&w=majority&appName=eva-u2-spring

spring.data.mongodb.database=discografica-db